# Generated by Django 2.2.3 on 2019-07-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendortraining', '0002_auto_20190725_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
